name: complaints
channels:
  - conda-forge
  - defaults
dependencies:
  - altair==4.2.0
  - numpy==1.23.5
  - pandas==1.4.4
  - pytest==7.2.0
  - requests==2.28.1
  - scikit_learn==1.1.3
  - pip:
    - docopt-ng==0.8.1