name: complaints
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.8
  - altair==4.2.0
  - numpy==1.23.5
  - pandas==1.4.4
  - pytest==7.2.0
  - requests==2.28.1
  - scikit-learn==1.1.3
  - altair_data_server==0.4.1
  - altair_saver==0.5.0
  - selenium==4.2.0
  - pip==22.3.1
  - pip:
    - docopt-ng==0.8.1
    - vl-convert-python==0.5.*